/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Client.Message;
import Client.Servente;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author julio
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public static String namePasta;
    public static String nameNota;
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        inNameNota = new javax.swing.JTextField();
        inNamePasta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        outDiretorio = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BLOCO DE NOTAS");

        jButton7.setText("Criar nova nota");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Criar nova pasta");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Visualizar nota");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Deletar nota");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        inNameNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inNameNotaActionPerformed(evt);
            }
        });

        inNamePasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inNamePastaActionPerformed(evt);
            }
        });

        jLabel2.setText("Pasta");

        jLabel3.setText("Nota");

        jButton4.setText("Deletar pasta");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Editar nota");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Visualizar pastas");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        outDiretorio.setEditable(false);
        outDiretorio.setColumns(20);
        outDiretorio.setRows(5);
        jScrollPane2.setViewportView(outDiretorio);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8))
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel2))
                            .addComponent(inNamePasta)
                            .addComponent(inNameNota)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inNamePasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inNameNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton8))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton6))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login.usuarioLog = "";
        String args = "sair";
        Message msgTosend = new Message(0,Servente.countIDMsg,"SAIR",9,args);
        Servente func = new Servente();
            Message replay = null;
            replay = func.doOperation(msgTosend);
            Servente.countIDMsg++;
            //JOptionPane.showMessageDialog(null, replay.getArguments());
            String statusLog = replay.getArguments();
        dispose();
        new Telas.Login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        new Telas.CriarNota().setVisible(true);
            
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        dispose();
        new Telas.CriarPasta().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void inNameNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inNameNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inNameNotaActionPerformed

    private void inNamePastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inNamePastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inNamePastaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (inNamePasta.getText().equals("") || inNameNota.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "CAMPO PASTA OU NOTA NÂO INFORMADO!");
        }else{
        String args = Login.usuarioLog+"-"+inNamePasta.getText()+"-"+inNameNota.getText();
        
        Message msgTosend = new Message(0,Servente.countIDMsg,"LERNOTA",4,args);
        Servente func = new Servente();
            Message replay = null;
            replay = func.doOperation(msgTosend);
            Servente.countIDMsg++;
            //JOptionPane.showMessageDialog(null, replay.getArguments());
            String statusLog = replay.getArguments();
            
            if (statusLog.equals("ERRO1")) {
                JOptionPane.showMessageDialog(null, "PASTA DE NOTAS NÂO EXISTE!");
            }else if (statusLog.equals("ERRO2")) {
                JOptionPane.showMessageDialog(null, "NOTA NÂO EXISTENTE!");
            }else{
                JOptionPane.showMessageDialog(null, statusLog);
                
            }
        }
        
        //JOptionPane.showMessageDialog(null, Menu.namePasta);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (inNamePasta.getText().equals("") || inNameNota.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "CAMPO PASTA OU NOTA NÂO INFORMADO!");
        }else{
        String args = Login.usuarioLog+"-"+inNamePasta.getText()+"-"+inNameNota.getText();
        
        Message msgTosend = new Message(0,Servente.countIDMsg,"DELETANOTA",5,args);
        Servente func = new Servente();
            Message replay = null;
            replay = func.doOperation(msgTosend);
            Servente.countIDMsg++;
            //JOptionPane.showMessageDialog(null, replay.getArguments());
            String statusLog = replay.getArguments();
            
            if (statusLog.equals("ERRO1")) {
                JOptionPane.showMessageDialog(null, "PASTA DE NOTAS NÂO EXISTE!");
            }else if (statusLog.equals("ERRO2")) {
                JOptionPane.showMessageDialog(null, "NOTA NÂO EXISTENTE!");
            }else if (statusLog.equals("CONCLUIDO")) {
                JOptionPane.showMessageDialog(null, "NOTA DELETADA!");
                dispose();
                new Telas.Menu().setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new Telas.VisualizaNota().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (inNamePasta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "CAMPO PASTA NÂO INFORMADO!");
        }else{
            String args = Login.usuarioLog+"-"+inNamePasta.getText();
            Message msgTosend = new Message(0,Servente.countIDMsg,"DELETAPASTA",8,args);
            Servente func = new Servente();
            Message replay = null;
            replay = func.doOperation(msgTosend);
            Servente.countIDMsg++;
            String statusLog = replay.getArguments();
            
            if (statusLog.equals("ERRO1")) {
                JOptionPane.showMessageDialog(null, "PASTA DE NOTAS NÂO EXISTE!");
            }else if (statusLog.equals("CONCLUIDO")) {
                JOptionPane.showMessageDialog(null, "PASTA DE NOTAS DELETADA!");
                dispose();
                new Telas.Menu().setVisible(true);
        }
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String args = Login.usuarioLog;
            Message msgTosend = new Message(0,Servente.countIDMsg,"LIST_PASTA",7,args);
            Servente func = new Servente();
            Message replay = null;
            replay = func.doOperation(msgTosend);
            Servente.countIDMsg++;
            String statusLog = replay.getArguments();
            String result;
            
            result="";
            String cont[] = statusLog.split("#");
            
            int i = Integer.parseInt(cont[1]);
            String msg = cont[0];
            String diretorios[] = msg.split("/");
            
            for (int j = 1; j <= i; j++) {
                String pasta = diretorios[j];
                String contPasta[] = pasta.split("-");
                
                int contArq = Integer.parseInt(contPasta[1]);
                String dirPasta = contPasta[0];
                String nomePasta[] = dirPasta.split("<>");
                result += "\n* "+nomePasta[0]+"\n";
                String arquivos[] = nomePasta[1].split(",");
                
                for (int k = 0; k < contArq; k++) {
                    result += "         "+arquivos[k]+"\n";
                }
            }
            
            outDiretorio.setText(result);
            
    }//GEN-LAST:event_jButton6ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inNameNota;
    private javax.swing.JTextField inNamePasta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea outDiretorio;
    // End of variables declaration//GEN-END:variables
}
